# Generated by Django 5.2.11 on 2026-02-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pin',
            field=models.IntegerField(default=0),
        ),
    ]
